services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: orga
      POSTGRES_USER: orga
      POSTGRES_PASSWORD: orga
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orga.local
      PGADMIN_DEFAULT_PASSWORD: orga
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
